/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as TeslimNoktalariRouteImport } from './routes/teslim-noktalari'
import { Route as TaleplerimRouteImport } from './routes/taleplerim'
import { Route as PuanlarimRouteImport } from './routes/puanlarim'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as IlanlarimRouteImport } from './routes/ilanlarim'
import { Route as EsyaEkleRouteImport } from './routes/esya-ekle'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IlanlarIndexRouteImport } from './routes/ilanlar.index'
import { Route as IlanlarItemIdRouteImport } from './routes/ilanlar.$itemId'

const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const TeslimNoktalariRoute = TeslimNoktalariRouteImport.update({
  id: '/teslim-noktalari',
  path: '/teslim-noktalari',
  getParentRoute: () => rootRouteImport,
} as any)
const TaleplerimRoute = TaleplerimRouteImport.update({
  id: '/taleplerim',
  path: '/taleplerim',
  getParentRoute: () => rootRouteImport,
} as any)
const PuanlarimRoute = PuanlarimRouteImport.update({
  id: '/puanlarim',
  path: '/puanlarim',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanlarimRoute = IlanlarimRouteImport.update({
  id: '/ilanlarim',
  path: '/ilanlarim',
  getParentRoute: () => rootRouteImport,
} as any)
const EsyaEkleRoute = EsyaEkleRouteImport.update({
  id: '/esya-ekle',
  path: '/esya-ekle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanlarIndexRoute = IlanlarIndexRouteImport.update({
  id: '/ilanlar/',
  path: '/ilanlar/',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanlarItemIdRoute = IlanlarItemIdRouteImport.update({
  id: '/ilanlar/$itemId',
  path: '/ilanlar/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esya-ekle': typeof EsyaEkleRoute
  '/ilanlarim': typeof IlanlarimRoute
  '/profil': typeof ProfilRoute
  '/puanlarim': typeof PuanlarimRoute
  '/taleplerim': typeof TaleplerimRoute
  '/teslim-noktalari': typeof TeslimNoktalariRoute
  '/yonetim': typeof YonetimRoute
  '/ilanlar/$itemId': typeof IlanlarItemIdRoute
  '/ilanlar/': typeof IlanlarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esya-ekle': typeof EsyaEkleRoute
  '/ilanlarim': typeof IlanlarimRoute
  '/profil': typeof ProfilRoute
  '/puanlarim': typeof PuanlarimRoute
  '/taleplerim': typeof TaleplerimRoute
  '/teslim-noktalari': typeof TeslimNoktalariRoute
  '/yonetim': typeof YonetimRoute
  '/ilanlar/$itemId': typeof IlanlarItemIdRoute
  '/ilanlar': typeof IlanlarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/esya-ekle': typeof EsyaEkleRoute
  '/ilanlarim': typeof IlanlarimRoute
  '/profil': typeof ProfilRoute
  '/puanlarim': typeof PuanlarimRoute
  '/taleplerim': typeof TaleplerimRoute
  '/teslim-noktalari': typeof TeslimNoktalariRoute
  '/yonetim': typeof YonetimRoute
  '/ilanlar/$itemId': typeof IlanlarItemIdRoute
  '/ilanlar/': typeof IlanlarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/esya-ekle'
    | '/ilanlarim'
    | '/profil'
    | '/puanlarim'
    | '/taleplerim'
    | '/teslim-noktalari'
    | '/yonetim'
    | '/ilanlar/$itemId'
    | '/ilanlar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/esya-ekle'
    | '/ilanlarim'
    | '/profil'
    | '/puanlarim'
    | '/taleplerim'
    | '/teslim-noktalari'
    | '/yonetim'
    | '/ilanlar/$itemId'
    | '/ilanlar'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/esya-ekle'
    | '/ilanlarim'
    | '/profil'
    | '/puanlarim'
    | '/taleplerim'
    | '/teslim-noktalari'
    | '/yonetim'
    | '/ilanlar/$itemId'
    | '/ilanlar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EsyaEkleRoute: typeof EsyaEkleRoute
  IlanlarimRoute: typeof IlanlarimRoute
  ProfilRoute: typeof ProfilRoute
  PuanlarimRoute: typeof PuanlarimRoute
  TaleplerimRoute: typeof TaleplerimRoute
  TeslimNoktalariRoute: typeof TeslimNoktalariRoute
  YonetimRoute: typeof YonetimRoute
  IlanlarItemIdRoute: typeof IlanlarItemIdRoute
  IlanlarIndexRoute: typeof IlanlarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teslim-noktalari': {
      id: '/teslim-noktalari'
      path: '/teslim-noktalari'
      fullPath: '/teslim-noktalari'
      preLoaderRoute: typeof TeslimNoktalariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taleplerim': {
      id: '/taleplerim'
      path: '/taleplerim'
      fullPath: '/taleplerim'
      preLoaderRoute: typeof TaleplerimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puanlarim': {
      id: '/puanlarim'
      path: '/puanlarim'
      fullPath: '/puanlarim'
      preLoaderRoute: typeof PuanlarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilanlarim': {
      id: '/ilanlarim'
      path: '/ilanlarim'
      fullPath: '/ilanlarim'
      preLoaderRoute: typeof IlanlarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esya-ekle': {
      id: '/esya-ekle'
      path: '/esya-ekle'
      fullPath: '/esya-ekle'
      preLoaderRoute: typeof EsyaEkleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilanlar/': {
      id: '/ilanlar/'
      path: '/ilanlar'
      fullPath: '/ilanlar/'
      preLoaderRoute: typeof IlanlarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilanlar/$itemId': {
      id: '/ilanlar/$itemId'
      path: '/ilanlar/$itemId'
      fullPath: '/ilanlar/$itemId'
      preLoaderRoute: typeof IlanlarItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EsyaEkleRoute: EsyaEkleRoute,
  IlanlarimRoute: IlanlarimRoute,
  ProfilRoute: ProfilRoute,
  PuanlarimRoute: PuanlarimRoute,
  TaleplerimRoute: TaleplerimRoute,
  TeslimNoktalariRoute: TeslimNoktalariRoute,
  YonetimRoute: YonetimRoute,
  IlanlarItemIdRoute: IlanlarItemIdRoute,
  IlanlarIndexRoute: IlanlarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
